### ISSUE TITLE
Modules do not work

### ISSUE THREAD

**Issue by MohammadRTX** [HuskyDG/Magisk-on-VMOS#3]
I tested all the modules and got this error رام marlin (ARM64) Xiaomi Note Eight
- Copying zip to temp directory
! This zip is not a Magisk Module!
! Installation failed
![Screenshot_۲۰۲۱-۱۰-۰۳-۱۹-۱۷-۴۳-۲۲۳_com vmos pro](https://user-images.githubusercontent.com/90418723/135761568-fe4ce2ef-7fd6-4c1d-893e-69353f938466.jpg)

**Comment by HuskyDG** [comment]
VMOS have many bugs...

VMOS is closed source... And virtual machine inside VMOS doesn't have its own **Selinux rule**

Because VMOS uses fake rootfs, that why i cannot make MagiskHide and Magisk module to work!

Read this: https://github.com/HuskyDG/VMOS-vs-VphoneGaGa

Also, please read README.md

>Only MagiskSU. MagiskHide cannot hide root and Magisk module cannot work. This is a experimental feature. If you want modules then don't expect it to work. Modules like MigiskHideProps are not working. So don't expect much.​

> As of now there is no working way for passing SafetyNet for playing games and apps that use it. 

VMOS will not be fully supported Magisk by these drawbacks
